# Generated by Django 5.0.14 on 2026-02-13 10:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeranFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=255)),
                ('abstrak', models.TextField(help_text='Keterangan singkat kegiatan')),
                ('nama_mitra', models.CharField(max_length=200)),
                ('lokasi_administratif', models.CharField(help_text='Format: Negara | Propinsi | Kabupaten | Desa', max_length=255)),
                ('koordinat', django.contrib.gis.db.models.fields.PointField(help_text='Titik koordinat lokasi mitra', srid=4326)),
                ('kategori_sdgs', models.IntegerField(choices=[(1, 'SDG 1'), (2, 'SDG 2'), (3, 'SDG 3'), (4, 'SDG 4'), (5, 'SDG 5'), (6, 'SDG 6'), (7, 'SDG 7'), (8, 'SDG 8'), (9, 'SDG 9'), (10, 'SDG 10'), (11, 'SDG 11'), (12, 'SDG 12'), (13, 'SDG 13'), (14, 'SDG 14'), (15, 'SDG 15'), (16, 'SDG 16'), (17, 'SDG 17')], verbose_name='Kategori SDGs')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='kegiatan_photos/')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL Berita')),
                ('tahun', models.IntegerField(help_text='Tahun kegiatan dilakukan')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan', to='api.kategorikegiatan')),
            ],
            options={
                'verbose_name': 'Peran FT UGM',
                'ordering': ['-tahun'],
            },
        ),
    ]
