# Generated by Django 5.0.14 on 2026-04-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peranft',
            name='abstrak',
            field=models.TextField(blank=True, help_text='Keterangan singkat kegiatan', null=True),
        ),
    ]
